// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8HGFhsoCUPVNZkZ4E71fkxTIgeGrGJK0',
    appId: '1:638788941756:web:ca330f325717a91ed55db9',
    messagingSenderId: '638788941756',
    projectId: 'litops-99d71',
    authDomain: 'litops-99d71.firebaseapp.com',
    storageBucket: 'litops-99d71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsJz8r15NWF1H9azEAqKnBRO3uZCwv6DM',
    appId: '1:638788941756:android:cf98bdd163b02ff0d55db9',
    messagingSenderId: '638788941756',
    projectId: 'litops-99d71',
    storageBucket: 'litops-99d71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWXwoMgnlTPGCMyuGyeuo87bgOYRK14_E',
    appId: '1:638788941756:ios:379b1702e480908fd55db9',
    messagingSenderId: '638788941756',
    projectId: 'litops-99d71',
    storageBucket: 'litops-99d71.firebasestorage.app',
    iosBundleId: 'com.litclub.litops',
  );
}
